# Generated by Django 3.2.8 on 2021-10-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_re', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_cast',
            name='cast_id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
    ]
