# Generated by Django 3.2.8 on 2021-11-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_re', '0003_chat_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_record',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
